import { Platform, StatusBar, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#f7f8fb',
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight ?? 0 : 0,
    paddingBottom: Platform.OS === 'android' ? 8 : 0,
  },
  container: {
    flex: 1,
  },
  header: {
    alignItems: 'center',
    borderBottomColor: '#dde2ea',
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  title: {
    color: '#111827',
    fontSize: 20,
    fontWeight: '700',
  },
  subtitle: {
    color: '#667085',
    fontSize: 13,
    marginTop: 2,
  },
  status: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  statusError: {
    backgroundColor: '#fef3f2',
  },
  statusText: {
    color: '#475467',
    fontSize: 13,
    flex: 1,
  },
  statusErrorText: {
    color: '#b42318',
  },
  progressTrack: {
    backgroundColor: '#e4e7ec',
    height: 3,
    marginHorizontal: 16,
    marginBottom: 8,
    overflow: 'hidden',
  },
  progressFill: {
    backgroundColor: '#0f766e',
    height: 3,
  },
  metrics: {
    color: '#475467',
    fontSize: 12,
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  cachePanel: {
    backgroundColor: '#ffffff',
    borderColor: '#dde2ea',
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    marginHorizontal: 16,
    marginBottom: 8,
    padding: 12,
  },
  cacheHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  cacheTitle: {
    color: '#111827',
    fontSize: 13,
    fontWeight: '700',
  },
  cacheMeta: {
    color: '#667085',
    fontSize: 12,
    marginTop: 2,
  },
  cacheError: {
    color: '#b42318',
    fontSize: 12,
    marginTop: 8,
  },
  cacheEmpty: {
    color: '#667085',
    fontSize: 12,
    marginTop: 8,
  },
  cacheRow: {
    alignItems: 'center',
    borderTopColor: '#eef2f6',
    borderTopWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 12,
    marginTop: 10,
    paddingTop: 10,
  },
  cacheModelCopy: {
    flex: 1,
  },
  cacheModelId: {
    color: '#111827',
    fontSize: 12,
    fontWeight: '600',
  },
  cacheModelMeta: {
    color: '#667085',
    fontSize: 12,
    marginTop: 2,
  },
  smallButton: {
    alignItems: 'center',
    backgroundColor: '#f2f4f7',
    borderColor: '#d0d5dd',
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 34,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  smallButtonText: {
    color: '#344054',
    fontSize: 12,
    fontWeight: '700',
  },
  deleteButton: {
    alignItems: 'center',
    backgroundColor: '#fff1f3',
    borderColor: '#fecdd6',
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 34,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  deleteButtonText: {
    color: '#b42318',
    fontSize: 12,
    fontWeight: '700',
  },
  inferenceStatus: {
    alignItems: 'center',
    backgroundColor: '#ecfdf3',
    borderColor: '#abefc6',
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 10,
    marginHorizontal: 16,
    marginBottom: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  inferenceStatusCopy: {
    flex: 1,
  },
  inferenceStatusTitle: {
    color: '#067647',
    fontSize: 13,
    fontWeight: '700',
  },
  inferenceStatusText: {
    color: '#344054',
    fontSize: 12,
    marginTop: 2,
  },
  messages: {
    gap: 10,
    padding: 16,
  },
  composer: {
    alignItems: 'flex-end',
    borderTopColor: '#dde2ea',
    borderTopWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 8,
    padding: 12,
  },
  input: {
    backgroundColor: '#ffffff',
    borderColor: '#cfd6e2',
    borderRadius: 8,
    borderWidth: 1,
    color: '#111827',
    flex: 1,
    fontSize: 15,
    maxHeight: 120,
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  button: {
    alignItems: 'center',
    backgroundColor: '#111827',
    borderRadius: 8,
    minHeight: 44,
    minWidth: 88,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: '#fef3f2',
    borderColor: '#fecdca',
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 44,
    minWidth: 72,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  secondaryButtonText: {
    color: '#b42318',
    fontSize: 14,
    fontWeight: '700',
  },
  disabled: {
    opacity: 0.45,
  },
});
